Remove -Wno-misleading-indentation
This option is not recognized by clang, so it produces an error when configured
with

  CC=clang ./configure

  error: unknown warning option '-Wno-misleading-indentation'; did you mean '-Wno-missing-declarations'? [-Werror,-Wunknown-warning-option]

This flag is only needed for cJSON.c. Deobfuscate that file just enough to
eliminate the misleading indentation warnings, then remove the warning flag from
Makefile.am.