Add x11_headers dependency to all targets that use it
This fixes the build for me since I have libX11 installed to a custom
prefix, so the default include path does not include libX11. This fixes
lots of instances of the following error:
../../libglvnd/include/EGL/eglplatform.h:109:10: fatal error: 'X11/Xlib.h' file not found

Signed-off-by: Alex Richardson <Alexander.Richardson@cl.cam.ac.uk>